### ISSUE TITLE
missing Microsoft.Phone.Controls.Toolkit

### ISSUE THREAD

**Issue by mtamony** [sgrebnov/jqmobile-metro-theme#16]
This is missing from the MetroThemeDemoApp

**Comment by abub** [comment]
Hi @mtamony, if you installed it using Nuget, it would have downloaded the toolkit for you. If you are doing it manually, you can get it from
http://silverlight.codeplex.com/

thanks

**Comment by sgrebnov** [comment]
You can also install this component manually - details are on home page under Prerequisite section
Silverlight for Windows Phone Toolkit
http://silverlight.codeplex.com/releases/view/71550#DownloadId=270984

**Comment by sgrebnov** [comment]
You can also install this component manually - details are on home page under Prerequisite section
Silverlight for Windows Phone Toolkit
http://silverlight.codeplex.com/releases/view/71550#DownloadId=270984

**Comment by sgrebnov** [comment]
You can also install this component manually - details are on home page under Prerequisite section
Silverlight for Windows Phone Toolkit
http://silverlight.codeplex.com/releases/view/71550#DownloadId=270984

**Comment by sgrebnov** [comment]
You can also install this component manually - details are on home page under Prerequisite section
Silverlight for Windows Phone Toolkit
http://silverlight.codeplex.com/releases/view/71550#DownloadId=270984

**Comment by sgrebnov** [comment]
You can also install this component manually - details are on home page under Prerequisite section
Silverlight for Windows Phone Toolkit
http://silverlight.codeplex.com/releases/view/71550#DownloadId=270984

**Comment by sgrebnov** [comment]
You can also install this component manually - details are on home page under Prerequisite section
Silverlight for Windows Phone Toolkit
http://silverlight.codeplex.com/releases/view/71550#DownloadId=270984
