### ISSUE TITLE
dateTimePicker

### ISSUE THREAD

**Issue by Mcs-developer** [sgrebnov/jqmobile-metro-theme#19]
Hi! 

Would you like to know how to implement the plugin "DateTimePicker"? in what order the js, and I follow the procedure in the example and is not working. I use the DateTimePicker in the index, but I want to deploy on another page. Thanks...

**Comment by olivierbloch** [comment]
Can you let us know what version of Cordova you are using?

**Comment by Mcs-developer** [comment]
Hi olivierbloch

I'm using Cordova 1.7

**Comment by olivierbloch** [comment]
I would have to double check with Sergey on this, but I'd say that the theme has been updated to support Cordova 1.9. Have you tried with this later version?
I will try to reproduce on my side. can you share the piece of code  you are using?

**Comment by Mcs-developer** [comment]
Hi ! 

I tried it with version 1.9 cordova, but equally it does not work. My scripts are as follows:

```
<script src="js/jquery.js" type="text/javascript"></script>
<script src="css/metro/jquery.mobile.metro.theme.init.js" type="text/javascript"></script>
<script src="js/jquery.mobile.js" type="text/javascript"></script>
<script src="js/jquery.globalstylesheet.js" type="text/javascript"></script>
<script src="js/jquery.mobile.themeswitcher.js"  type="text/javascript"></script>
<script src="js/jquery.mobile.fixedToolbar.polyfill.js" type="text/javascript"></script>


<script src="js/progress-bar.js" type="text/javascript"></script>
<script src="js/toggle-button.js" type="text/javascript"></script>
<script src="js/app-bar.js" type="text/javascript"></script>
<script src="js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="js/mobiscroll-1.5.3.js" type="text/javascript"></script>

<script src="js/cordova-1.9.0.js" type="text/javascript"></script>


<script type="text/javascript">
    $.themesDir = 'css/';

    $().ready(function () {
        if (!$.browser.msie) {
            $("#noteIeRequired").show();
        }

        // special title when run in Cordova environment
        if (typeof window.external.Notify !== "undefined") {
            document.getElementById("appTitle").innerHTML = "Theme overview";
        }
    });

    // allows to use the page in NON cordova environment
    if (typeof window.external.Notify !== "undefined") {

        var head = document.getElementsByTagName("head")[0];

        //            var sc1 = document.createElement("script");
        //            sc1.src = "js/cordova-1.5.0.js";
        //            (head || document.body).appendChild(sc1);


        var sc2 = document.createElement("script");
        sc2.src = "js/phoneTheme.js";
        (head || document.body).appendChild(sc2);

        var sc3 = document.createElement("script");
        sc3.src = "js/jquery.cordova.metro.themeswitcher.js";
        (head || document.body).appendChild(sc3);

        var sc4 = document.createElement("script");
        sc4.src = "js/backButtonHandler.js";
        (head || document.body).appendChild(sc4);

        var sc5 = document.createElement("script");
        sc5.src = "js/dateTimePicker.js";
        (head || document.body).appendChild(sc5);
    }

</script>


<script type="text/javascript" src="model/conn.js"></script>
<script type="text/javascript" src="model/GenericFunctions.js"></script>
<script type="text/javascript" src="index.js"></script>
<script type="text/javascript" src="controller/initialPageController.js"></script>
```

On page initalpage.html is where I have to type datetimepicker textbox, but when I select it makes no action.

**Comment by sgrebnov** [comment]
Hey, @Mcs-developer 
Could you please check that you have the following cs files as part of your project: DateTimePicker.cs, DateTimePickerTask.cs
https://github.com/sgrebnov/jqmobile-metro-theme/tree/master/samples/WindowsPhone/MetroThemeDemoApp/MetroThemeDemoApp/Plugins

They require for the app to have a reference to Silverlight Toolkit to Windows Phone
http://silverlight.codeplex.com/releases/view/75888

**Comment by Mcs-developer** [comment]
Yes, I have these files and I have installed the sdk

**Comment by Mcs-developer** [comment]
Could you give me the order of the scripts?  I'm doing it the way that is in the example and not working

**Comment by sgrebnov** [comment]
The order seems to be correct. Could you please also check you initialize the date time fields, like 

```
        $(document).ready(function () {
            // cordova environment
            if(navigator.plugins && typeof navigator.plugins.dateTimePicker !== "undefined"){
                // Date with external button
                $('#date1').scroller({ mode: 'clickpick' });
                // Time
                $('#date2').scroller({ preset: 'time',mode: 'clickpick' });
```

Full example is available at https://github.com/sgrebnov/jqmobile-metro-theme/blob/master/samples/jqm-public-demo/pages/date-time.html

**Comment by Mcs-developer** [comment]
Hi 
In the console output when I use your example, I can see this line   Log:"Run PhoneGap dateTimePicker plugin instead of html plugin version" and when I use my project does not appear in the console output

**Comment by sgrebnov** [comment]
Can you share the code?

The line you mentioned is a part of mobiscroll-1.5.3.js. 

```
    /**
    * Shows the scroller instance.
    */
    this.show = function () {

        if (s.disabled || visible) return false;

        s.beforeShow(elm, this);

        if (navigator.plugins && navigator.plugins.dateTimePicker){

            console.log('Run PhoneGap dateTimePicker plugin instead of html plugin version');
```

You can trace the problem using additional console.log ("lineN") statements. Could you please try to add console.log ("Show is called"); right after this.show = function () { and see if it is called

**Comment by Mcs-developer** [comment]
Hi ! 

Already tried what you said but I see that the code is not going through that line. What can be the error?. The order of the scripts?

**Comment by Mcs-developer** [comment]
Hi !

I was able to solve the problem of datetimepicker, the solution was in the order they loaded the javascript. Thanks.
