### ISSUE TITLE
Wrap as a NuGet Package

### ISSUE THREAD

**Issue by abub** [sgrebnov/jqmobile-metro-theme#7]
the template should be available as a NuGet package
see these for details
http://nuget.codeplex.com/
http://msdn.microsoft.com/en-us/magazine/hh547106.aspx

**Comment by sgrebnov** [comment]
Ideas regarding supported package types/options.
1.  Baseline
   Single Theme file  only (css)
2.  Baseline + plugins
   a)  Main theme file (css)
   b)  All additional plugins, for example AppBar (css+js)
3.  PhoneGap version
   a)  Baseline + plugins (see above)
   b)  PhoneGap plugins (theme swithcher, DateTime picker – js, css, cs)
   c)  Silverlight Toolkit for Windows Phone   dll)
   Other ideas:
4.  Special option to automatically replace default theme css in html files (Dialog prompt or additional command line parameter)
5.  Option #3 can be detected/applied automatically

**Comment by sgrebnov** [comment]
1. Run Cordova-1.5.0-Starter
2. Run the following command on Package Manager  Console (nuget)
   Install-Package jQMobileMetroTheme -Version 1.0.4 
3. Set www/metroStartPage.html as Cordova start page.
4. Run

All plugins including back button handling  and theme switcher work correct. Many images are not displayed - to be investigated.

**Comment by abub** [comment]
Please do an additional package that does the option #2 as well: baseline and jQM plugins.. no phonegap stuff

**Comment by sgrebnov** [comment]
Fat - 
Install-Package jQMMetroCordovaTheme -Version 0.9.3

Lite - 
Install-Package jQMMetroTheme -Version 0.9.0
